services:
  app:
    environment:
      CLASSIFICATION_ANALYZER_TOKEN: ""
      CLASSIFICATION_ANALYZER_TOKEN_FILE: /run/secrets/analyzer_token
    secrets:
      - analyzer_token

  analyzer:
    environment:
      ANALYZER_TOKEN: ""
      ANALYZER_TOKEN_FILE: /run/secrets/analyzer_token
    secrets:
      - analyzer_token

secrets:
  analyzer_token:
    file: ${ANALYZER_TOKEN_HOST_FILE:-./secrets/analyzer_token}
