services:
  app:
    environment:
      DATABASE_PASSWORD: ""
      DATABASE_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password

  postgres:
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password

secrets:
  postgres_password:
    file: ${POSTGRES_PASSWORD_HOST_FILE:-./secrets/postgres_password}
