services:
  app:
    environment:
      JWT_SECRET: ""
      JWT_SECRET_FILE: /run/secrets/jwt_secret
    secrets:
      - jwt_secret

secrets:
  jwt_secret:
    file: ${JWT_SECRET_HOST_FILE:-./secrets/jwt_secret}
