name: CI & Release

on:
  push:
    branches: [ main ]
    tags: 
      - 'v*'
  pull_request:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: music
          POSTGRES_PASSWORD: music
          POSTGRES_DB: music
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U music"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      GO_VERSION: "1.22"
      NODE_VERSION: "20"

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install & Build Frontend
        working-directory: web
        run: |
          npm ci
          npm run build 

      - name: Go Mod Download
        run: go mod download

      - name: Go Test
        run: go test ./...

      - name: Cross-Platform Build
        run: |
          export CGO_ENABLED=0
          GOOS=linux GOARCH=amd64 go build -v -o music-server-linux-amd64 ./cmd/server
	  GOOS=linux GOARCH=arm64 go build -v -o music-server-linux-arm64.exe ./cmd/server
          
          # Windows
          GOOS=windows GOARCH=amd64 go build -v -o music-server-windows-amd64.exe ./cmd/server
	  GOOS=windows GOARCH=arm64 go build -v -o music-server-windows-arm64.exe ./cmd/server

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            music-server-linux-amd64
            music-server-windows-amd64.exe
	    music-server-linux-arm64
            music-server-windows-arm64.exe
          generate_release_notes: true
          draft: false
          prerelease: false